apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: charttest1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-username/demo-dev.git
    targetRevision: main
    path: HelmCharts/ChartTest1
  destination:
    server: https://kubernetes.default.svc
    namespace: test-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
